### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "aauser",
  "userId": "idaapu1",
  "password": "paaa",
  "phoneNumber": "010-7777-7777",
  "role": "ROLE_USER"
}

### 로그인 - 파트너
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "userId": "idaap",
  "password": "paaa"
}


### 로그인 - 유저
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "userId": "idaapu1",
  "password": "paaa"
}
