### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "aa",
  "userId": "idaap",
  "password": "paaa",
  "phoneNumber": "010-7777-7777",
  "role": "ROLE_PARTNER"
}

### eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZGFhcCIsInJvbGVzIjpbIlJPTEVfUEFSVE5FUiJdLCJpYXQiOjE3MDk3MzE4MTcsImV4cCI6MTcwOTczNTQxN30.42VdccZ0OzdO6XKY1zP7YhZH8dVJkYdaJOnnM8R__jU


### 로그인
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "userId": "idaap",
  "password": "paaa"
}
